language: java
jdk:
- oraclejdk8
env:
  matrix:
  - IDEA_VERSION=15.0.5
  - IDEA_VERSION=2016.1
install: ./gradlew extractIdeaSdk
script: ./gradlew build -PideaVersion=${IDEA_VERSION} -Pversion=${TRAVIS_TAG:-dev}
deploy:
  provider: releases
  api_key:
    secure: HFLxsw+X2QpVZz5mlFrr2QoKu5044uutpfzVl06114RooZpQPB5rmRJi5PEprL0VZOdFfnKquNUElJbKkk8jIiJlUDQm3FWtFcS+lA3vRRVXbT6dUaL5uzF47kYkEHcOMP6uL/jHn2DfjQoRlSgmNREgV71tJIC9E4XPEfsNkoWpcCpUncLtLi6qJPlFbT248VjSKsisYo7k9Ruhj6lwVqcUYYQY0LJ7IA4x5RcJyg0nTpoclwLFi/+burXk/OUjJzcgX8x+bQuJf0ajLWKYYz+wHBa1xVncUtH3cFpaS/TubJfAt6cUPTFz+XcAUwBpHQP9btOINHHEauX/vxeP64R7NCaF974CtXlsJzOYl7o09woCVRYogGRk3WKsxLxcK0fJ3IyEjElDTMbZPtzxV/vU4DdgZp8aP+9luC+twa3iFP3zkp0CHbGxcElO+DeshHu+YocHL1E2bBr1QXwU9cBvHRNZPgWocv/S909ZDGr5Hnc8ewudtQBSwZHaWMkLa6u3GRm1CTT1aaKD6sMQJcL+0FkObZ1ic7C5J0d2Lars4nl3QiE13xYq4MRK4HFEP0LZQyiIprsDQlvEGhgQysXXHLKBDr0pmZzDDInd5vbVHrvGHkJ+HbAFjyrJfSzFptNzr/uWoFog5DMEXLoqL/vTeNVq7Fw/XqnknhO+rtc=
  file: build/distributions/idea-fitnesse-${TRAVIS_TAG}.zip
  on:
    repo: fitnesse/idea-fitnesse
    tags: true
    condition: $IDEA_VERSION = 15.0.5
sudo: false
cache:
  directories:
  - $HOME/.gradle
  - lib
